GET http://localhost:3000/items



### 2. Добавить новое кольцо (POST)
POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Кольцо «Звездная пыль»",
    "price": 45000,
    "material": "Платина"
}


### 3. Обновить цену изделия (PUT)
PUT http://localhost:3000/items/1
Content-Type: application/json

{
    "price": 100000
}

### 4. Удалить изделие (DELETE)
DELETE http://localhost:3000/items/1776121548060